### ISSUE TITLE
Release 1.3.3 not found for bower + different channel for legacy ionic versions that support bower 

### ISSUE THREAD

**Issue by almothafar** [driftyco/ionic-v1#234] opened 2017-03-26 09:00 UTC
I think Ionic 1.3.3 must still support bower, also, I think ionic 1 must be separated new channel rather than the ionic that reflect latest version (currently is Ionic 2.3.0), maybe use `ionic-v1` instead of `ionic` so we get the legacy versions instead?

I just wonder if ionic is no more released for bower, why I see them here, and why I can't see 1.3.3 version

```
bower ionic#1.3.3           not-cached https://github.com/driftyco/ionic.git#1.3.3
bower ionic#1.3.3              resolve https://github.com/driftyco/ionic.git#1.3.3
bower ionic#>=0.9.27            cached https://github.com/driftyco/ionic.git#2.3.0
bower ionic#>=0.9.27          validate 2.3.0 against https://github.com/driftyco/ionic.git#>=0.9.27
bower ionic#1.3.3         ENORESTARGET No tag found that was able to satisfy 1.3.3

Additional error details:
Available versions in https://github.com/driftyco/ionic.git: 2.3.0, 2.2.0, 2.1.0, 2.0.1, 2.0.0, 2.0.0-rc.6, 2.0.0-rc.5, 2.0.0-rc.4, 2.0.0-rc.3, 2.0.0-rc.2, 2.0.0-rc.1, 2.0.0-rc.0, 2.0.0-beta.11, 2.0.0-beta.10, 2.0.0-beta.9, 2.0.0-beta.8, 2.0.0-beta.7, 2.0.0-bet
a.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.3, 2.0.0-beta.2, 2.0.0-beta.1, 2.0.0-beta.0, 2.0.0-alpha.57, 2.0.0-alpha.56, 2.0.0-alpha.55, 2.0.0-alpha.54, 2.0.0-alpha.53, 2.0.0-alpha.52, 1.3.2, 1.3.1, 1.3.0, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.1,
 1.0.0, 1.0.0, 1.0.0-rc.5, 1.0.0-rc.4, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 1.0.0-rc.0, 1.0.0-beta.5b, 1.0.0-beta.10-nightly-16570, 1.0.0-beta.14, 1.0.0-beta.13, 1.0.0-beta.12, 1.0.0-beta.11, 1.0.0-beta.10, 1.0.0-beta.9, 1.0.0-beta.8, 1.0.0-beta.7, 1.0.0-beta.6,
 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 0.9.27, 0.9.26, 0.9.25, 0.9.24, 0.9.23, 0.9.22-alpha, 0.9.21-alpha, 0.9.20-alpha, 0.9.19-alpha, 0.9.18-alpha, 0.9.17-alpha, 0.9.16-alpha, 0.9.15-alpha, 0.9.14-alpha, 0.9.13-alpha, 0.9.12-alp
ha, 0.9.11-alpha, 0.9.10-alpha

```

Thanks,

**Comment by mlynch** [comment] 2017-03-27 19:46
Duplicate of #218

**Closed by mlynch** 2017-03-27 19:46 UTC
